# -----------------------------------------------------------------------------
# GitHub Actions 連携用の出力値
# -----------------------------------------------------------------------------
# terraform apply 後に GitHub の Variables へ設定する値です。
# 対応例:
# - github_actions_role_arn -> AWS_ROLE_ARN
# - deploy_artifact_bucket  -> DEPLOY_BUCKET
# - ec2_instance_id         -> EC2_INSTANCE_ID
output "github_actions_role_arn" {
  description = "IAM role ARN to set in GitHub Actions variable AWS_ROLE_ARN."
  value       = aws_iam_role.github_actions_deploy.arn
}

output "github_oidc_provider_arn" {
  description = "GitHub OIDC provider ARN used in trust relationship."
  value       = local.github_oidc_provider_arn
}

# -----------------------------------------------------------------------------
# 稼働基盤の出力値
# -----------------------------------------------------------------------------
# デプロイ後の手動確認や障害調査で使う値です。
output "ec2_instance_id" {
  description = "EC2 instance ID used by GitHub Actions deployment."
  value       = aws_instance.web.id
}

output "ec2_public_ip" {
  description = "Public IP of EC2 web server."
  value       = aws_instance.web.public_ip
}

output "deploy_artifact_bucket" {
  description = "S3 bucket used to store deployment artifacts."
  value       = aws_s3_bucket.artifacts.bucket
}

# -----------------------------------------------------------------------------
# 公開エンドポイント / DB接続情報の出力値
# -----------------------------------------------------------------------------
# この構成では ALB DNS が主な公開入口になります。
output "alb_dns_name" {
  description = "Public ALB DNS name for application access."
  value       = aws_lb.web.dns_name
}

output "rds_endpoint" {
  description = "MySQL RDS endpoint."
  value       = aws_db_instance.mysql.endpoint
}

output "rds_database_name" {
  description = "MySQL database name."
  value       = aws_db_instance.mysql.db_name
}

output "rds_master_username" {
  description = "MySQL master username."
  value       = aws_db_instance.mysql.username
}

output "rds_master_password" {
  description = "MySQL master password generated by Terraform."
  value       = random_password.db_master.result
  sensitive   = true
}
# 重要:
# - sensitive = true で通常出力では隠せますが、値自体は state に残ります。
#   state へのアクセス権は厳格に管理してください。
