output "github_actions_role_arn" {
  description = "IAM role ARN to set in GitHub Actions variable AWS_ROLE_ARN."
  value       = aws_iam_role.github_actions_deploy.arn
}

output "github_oidc_provider_arn" {
  description = "GitHub OIDC provider ARN used in trust relationship."
  value       = local.github_oidc_provider_arn
}

output "ec2_instance_id" {
  description = "EC2 instance ID used by GitHub Actions deployment."
  value       = aws_instance.web.id
}

output "ec2_public_ip" {
  description = "Public IP of EC2 web server."
  value       = aws_instance.web.public_ip
}

output "deploy_artifact_bucket" {
  description = "S3 bucket used to store deployment artifacts."
  value       = aws_s3_bucket.artifacts.bucket
}

output "alb_dns_name" {
  description = "Public ALB DNS name for application access."
  value       = aws_lb.web.dns_name
}

output "rds_endpoint" {
  description = "MySQL RDS endpoint."
  value       = aws_db_instance.mysql.endpoint
}

output "rds_database_name" {
  description = "MySQL database name."
  value       = aws_db_instance.mysql.db_name
}

output "rds_master_username" {
  description = "MySQL master username."
  value       = aws_db_instance.mysql.username
}

output "rds_master_password" {
  description = "MySQL master password generated by Terraform."
  value       = random_password.db_master.result
  sensitive   = true
}
